version: '3'
services:
  litespeed:
    image: litespeedtech/openlitespeed:latest
    volumes:
        - ./sites:/var/www/vhosts/
        - ./php.ini:/usr/local/lsws/lsphp74/etc/php/7.4/litespeed/php.ini
    ports:
      - 80:80
      - 443:443
      - 7080:7080
      
  mysql:
    image: mariadb:10.3.17
    command: --max_allowed_packet=256M
    volumes:
       - db:/var/lib/mysql:delegated
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    ports:
      - 8080:80
      - 8443:443
    environment:
        DATABASE_HOST: mysql

volumes:
   db:
